//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace veterinaria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mascota
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mascota()
        {
            this.consultaMedica = new HashSet<consultaMedica>();
        }
    
        public int idMascota { get; set; }
        public string nombreMascota { get; set; }
        public string sexo { get; set; }
        public string raza { get; set; }
        public string tipoAnimal { get; set; }
        public System.DateTime fechaIngreso { get; set; }
        public System.DateTime fechaNacimiento { get; set; }
        public string nombreDueno { get; set; }
        public string telefonoDueno { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<consultaMedica> consultaMedica { get; set; }
    }
}
